name: DOTDOTGOOSE

on:
  #schedule:
  #  - cron:  '55 */6 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - shell: pwsh
        env:
          CHOCO_API_KEY: ${{ secrets.CHOCO_API_KEY }}
        run: |
          choco apikey --key $env:CHOCO_API_KEY --source https://push.chocolatey.org/
          
      - name: Chocolatey
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: -h

      - name: Script
        env:
          CHOCO_API_KEY: ${{ secrets.CHOCO_API_KEY }}
          ACTIONS_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
          PST_KEY: ${{ secrets.PST_KEY }}
          PST_SECRET: ${{ secrets.PST_SECRET }}
          PST_TOKEN: ${{ secrets.PST_TOKEN }}
          PST_TOKEN_SECRET: ${{ secrets.PST_TOKEN_SECRET }}
          TELEGRAM: ${{ secrets.TELEGRAM }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run:  |
          $Version = ([xml](Get-Content ./dotdotgoose/dotdotgoose.nuspec)).package.metadata.version
          # Invoke-WebRequest -Uri "https://biodiversityinformatics.amnh.org/open_source/dotdotgoose/index.html" -OutFile "DDG.html"
          # $Source = Get-Content -path DDG.html
          # $Source -match '<ul class="local-list"> <li>[0-9]{4}-[0-9]{2}-[0-9]{2} - version ([0-9]+(\.[0-9]+)+) '
          # $tag = $matches[1]
          $tag = "1.5.2"
          
          echo $Version
          echo $tag
          
          if ( $tag -eq $Version )
          {
          echo 'Last version already exist'
          #Remove-Item DDG.html
          }
          else
          {
          ./send_dotdotgoose.ps1
          #Remove-Item DDG.html
          }
