name: HOMEBANK

on:
  schedule:
    - cron:  '25 */6 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}
      - shell: pwsh
        env:
          CHOCO_API_KEY: ${{ secrets.CHOCO_API_KEY }}
        run: |
          choco apikey --key $env:CHOCO_API_KEY --source https://push.chocolatey.org/
          
      - name: Chocolatey
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: upgrade chocolatey

      - name: Run scripts and commit
        run:  |
          $Version = ([xml](Get-Content ./homebank/homebank.nuspec)).package.metadata.version
          Invoke-WebRequest -Uri "http://homebank.free.fr/en/downloads.php" -OutFile "HOMEBANK.html"          
          $Source = Get-Content -path HOMEBANK.html -raw
          $Source -match 'The latest <b>([0-9]+(\.[0-9]+)+) stable</b>'
          $tag = $matches[1]
          echo $Version
          echo $tag
          Start-Sleep -Seconds 5
          if ( $tag -eq $Version )
          {
          echo 'Last version already exist'
          Remove-Item HOMEBANK.html
          }
          else
          {
          ./send_homebank.ps1
          Remove-Item HOMEBANK.html
          git config --local user.email "a-d-r-i@outlook.fr"
          git config --local user.name "A-d-r-i"
          git add .
          git commit -m "[Bot] Update files - Homebank" --allow-empty
          git tag -a test-homebank-v$tag -m "Homebank - version $tag"
          git push -f && git push --tags
          $twitter = (Select-String -Path config.txt -Pattern "twitter=(.*)").Matches.Groups[1].Value
          if ( $twitter -eq "y" )
          {
          Install-Module PSTwitterAPI -Force
          Import-Module PSTwitterAPI
          $OAuthSettings = @{
          ApiKey = "${{ secrets.PST_KEY }}"
          ApiSecret = "${{ secrets.PST_SECRET }}"
          AccessToken = "${{ secrets.PST_TOKEN }}"
          AccessTokenSecret = "${{ secrets.PST_TOKEN_SECRET }}"
          }
          Set-TwitterOAuthSettings @OAuthSettings
          Send-TwitterStatuses_Update -status "Homebank v$tag push now on @chocolateynuget ! 
          
          Link: https://community.chocolatey.org/packages/homebank/$tag
          #homebank #release #opensource
          "
          }
          }
