name: MENDELEY-RM-AUTO-UPDATE

on:
  schedule:
    - cron:  '0 */6 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}
      - shell: pwsh
        env:
          CHOCO_API_KEY: ${{ secrets.CHOCO_API_KEY }}
        run: |
          choco apikey --key $env:CHOCO_API_KEY --source https://push.chocolatey.org/
          
      - name: Chocolatey
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: upgrade chocolatey

      - name: Run scripts and commit
        run:  |
          $Version = ([xml](Get-Content ./mendeley-reference-manager/mendeley-reference-manager.nuspec)).package.metadata.version
          $ie = New-Object -comObject InternetExplorer.Application
          $ie.navigate('https://www.mendeley.com/release-notes-reference-manager')
          while ($ie.ReadyState -ne 4) { Start-Sleep -Seconds 1 }
          $null = $ie.Document.body.innerhtml -match '<div class="views-field views-field-title"><span class="field-content"><a href="/release-notes-reference-manager/v([0-9]+(\.[0-9]+)+)">Reference Manager'
          $ie.Quit()
          echo $matches[1]
          echo $Version
          Start-Sleep -Seconds 5
          echo $tag
          Start-Sleep -Seconds 5
          if ( $tag -eq $Version )
          {
          echo 'Last version already exist'
          }
          else
          {
          ./send_mendeley-reference-manager.ps1
          git config --local user.email "a-d-r-i@outlook.fr"
          git config --local user.name "A-d-r-i"
          git add .
          git commit -m "[Bot] Update files - Mendeley - RM" --allow-empty
          git tag -a mendeley-rm-v$tag -m "Mendeley-Reference-Manager - version $tag"
          git push -f && git push --tags
          }
