name: NOTIFICATION-DEBUG

on:
  workflow_dispatch:

env:
    PST_KEY: ${{ secrets.PST_KEY }}
    PST_SECRET: ${{ secrets.PST_SECRET }}
    PST_TOKEN: ${{ secrets.PST_TOKEN }}
    PST_TOKEN_SECRET: ${{ secrets.PST_TOKEN_SECRET }}
    TELEGRAM: ${{ secrets.TELEGRAM }}
    CHAT_ID: ${{ secrets.CHAT_ID }}
    MASTODON: ${{ secrets.MASTODON }}

jobs:
  NOTIFICATION-DEBUG:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: PUSH_TWITTER
        if: always()
        run: ./DEBUG/twitter.ps1
        
      - name: PUSH_TELEGRAM
        if: always()
        run: ./DEBUG/telegram.ps1

      - name: PUSH_MASTODON
        if: always()
        run: ./DEBUG/mastodon.ps1

